runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico$
  static_files: static/favicon.ico
  upload: favicon\.ico$
- url: /add.*
  script: main.app
  login: admin
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
